services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypas
      POSTGRES_USER: retool
      POSTGRES_DB: retool
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data: 
